spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lost_and_found_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    root-password: root_password
    username: db_username
    password: db_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always

external:
  api:
    base-url: http://localhost:8081 # Point to the WireMock container
user-service:
  url: http://localhost:8081/
