services:
  mysql:
    image: mysql:8.4
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lost_and_found_db
      MYSQL_USER: db_username
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password" ]
        interval: 10s
        timeout: 5s
        retries: 5

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-service
    ports:
      - "8081:8080" # Expose WireMock on port 8081
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings # Map the directory for predefined stubs
  app:
    build: .
    container_name: my_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lost_and_found_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: db_username
      SPRING_DATASOURCE_PASSWORD: db_password
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  mysql_data:
